LOG_FILE = 'utils/logs/testlogs.log'
DEFAULT_LIST_NAMES = ['Default List', 'New list']
PERM_MENU_ITEMS = ['Default List', 'Create new list']
LIST_NAME_01 = 'Today\'s To-Do\'s'
LIST_NAME_02 = 'Second List'
UPDATED_LIST_NAME_02 = 'Third List'
LIST_NAME_03 = 'My List'
TASK_NAME_01 = 'Item Alpha'
TASK_DETAIL_01 = 'Aenean pharetra magna ac placerat'
SAMPLE_TASKS = ['Item One', 'Item Bravo', 'Task Three']
JUNK_01 = "&%^*(!@#$)^$%#@!55(^&!Fz)!"
JUNK_02 = "BbMm##@@45!&"
